#!/bin/bash
# Step-by-step Interactive Testing Guide

echo "======================================================"
echo "  STUFF LENDING SYSTEM - INTERACTIVE TESTING GUIDE"
echo "======================================================"
echo ""

echo "STEP 1: Get Current Member and Item IDs"
echo "Run this command to see current members and items:"
echo ""
echo "  ./gradlew run"
echo ""
echo "Then choose:"
echo "  2 (List Members) - Note the member IDs"
echo "  5 (List Items) - Note the item IDs" 
echo "  0 (Exit)"
echo ""

echo "STEP 2: Test with Actual IDs"
echo "Now you can test operations that need IDs:"
echo ""
echo "CREATE ITEM (Option 4):"
echo "  - Name: Test Item"
echo "  - Category: OTHER"
echo "  - Description: Test description"
echo "  - Cost per day: 15.0"
echo "  - Owner ID: [use member ID from step 1]"
echo ""

echo "VIEW ITEM DETAILS (Option 6):"
echo "  - Item ID: [use item ID from step 1 or newly created]"
echo ""

echo "CREATE CONTRACT (Option 9):"
echo "  - Borrower ID: [different member than item owner]"
echo "  - Item ID: [any available item]"
echo "  - Start day: 1"
echo "  - End day: 3"
echo ""

echo "STEP 3: Quick Test Commands"
echo ""
echo "Test basic operations (no IDs needed):"
echo "  echo -e \"2\\n5\\n10\\n11\\n0\" | ./gradlew run --quiet"
echo ""
echo "Test add member:"
echo "  echo -e \"1\\nNew User\\n555-0123\\nnew@test.com\\n2\\n0\" | ./gradlew run --quiet"
echo ""
echo "Test verbose display:"
echo "  echo -e \"3\\n0\" | ./gradlew run --quiet"
echo ""

echo "STEP 4: Full Interactive Session"
echo "For complete testing, run:"
echo "  ./gradlew run"
echo ""
echo "And follow this sequence:"
echo "  1. List members (2) and items (5) to get IDs"
echo "  2. Add a new member (1)"
echo "  3. Create an item for the new member (4)"
echo "  4. Create a contract (9)"
echo "  5. List contracts (10)"
echo "  6. View item with contracts (6)"
echo "  7. Advance day (11)"
echo "  8. Exit (0)"
echo ""

echo "======================================================"
